name: Deploy To S3
on:
  push:
    branches:
      - dev
      - main
jobs:
  dev:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Load APP ENV
        run: |
          cat << EOF > apps/portal/.env.dev.local
          VITE_API_BASE_URL=https://at.dev.silkdigital.io/api/v1
          VITE_FORM_BUILDER_URL=https://ft.dev.silkdigital.io
          VITE_FE_URL=https://at.dev.silkdigital.io
          VITE_EMAIL_BUILDER_URL=https://et.dev.silkdigital.io
          EOF

      - name: Build
        run: |
          yarn
          yarn prepare
          yarn build:dev

      - name: Upload to s3
        run: |
          tar -zcvf dist.tar.gz dist
          aws s3 cp ./dist.tar.gz s3://auto-send-message-dev/dev/
          
      # - name: Run jenkins build
      #   run: |
      #     curl ${{ secrets.DEV_JENKINS_BUILD_URL }}

  main:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Load APP ENV
        run: |
          cat << EOF > apps/portal/.env.dev.local
          VITE_API_BASE_URL=https://at.ttshop.io/api/v1
          VITE_FORM_BUILDER_URL=https://ft.ttshop.io
          VITE_FE_URL=https://at.ttshop.io
          VITE_EMAIL_BUILDER_URL=https://et.ttshop.io
          EOF

      - name: Build
        run: |
          yarn
          yarn prepare
          yarn build:dev

      - name: Upload to s3
        run: |
          tar -zcvf dist.tar.gz dist
          aws s3 cp ./dist.tar.gz s3://auto-send-message-dev/prod/